### ISSUE TITLE
Service does not start when UID 1000 doesn't exist

### ISSUE THREAD

**Issue by Nosrob** [liaralabs/swizzin_dashboard#13]
On my machine I have 3 users with UIDs 1001, 1002, and 1003. No user exists with UID 1000, leaving the python service unable to start. I _think_ the users were set up originally with Swizzin, but it was a long time ago so I can't say for sure.

In swizzin.cfg, ADMIN_USER has been correctly set to my user however in  /core/config.py line 4 causes the issue. The error is easily reproduced:

```python
>>> import pwd
>>> pwd.getpwuid(1001).pw_name
'my_user'
>>> pwd.getpwuid(1000).pw_name
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 'getpwuid(): uid not found: 1000'
```

I was able to make it work for now by putting my correct UID in config.py, maybe it would be better to make swizzin.cfg keep the priority on this parameter instead?

**Comment by liaralabs** [comment]
Fixed with 5c8e6bb3e45db3a2f0d0df4d0c2f9aa002f08e5b
