### ISSUE TITLE
Display of Disk Usage of additional mount points

### ISSUE THREAD

**Issue by NightHammer1000** [liaralabs/swizzin_dashboard#47]
For Example:

I have my entire Storage mounted as an ZFS Pool at /storage

A way to display that as well would be awesome.

**Comment by dctorrent1337** [comment]
I have modified my local installation to perform this as well, I have a pending PR for that:

https://github.com/swizzin/swizzin_dashboard/pull/50

**Comment by brettpetch** [comment]
https://github.com/swizzin/swizzin_dashboard/pull/50

**Comment by brettpetch** [comment]
@liaralabs we can close this issue now :)
