### ISSUE TITLE
Feature request: specify full domain/address

### ISSUE THREAD

**Issue by flying-sausages** [liaralabs/swizzin_dashboard#6]
All the docs I can find now point to baseurl, however I'd like to make items to applications that live on subdomains and/or completely outside the domain

**Comment by liaralabs** [comment]
From the docs 😉 

`urloverride` - A complete override of the URL. If true, will supercede a baseurl/scheme definition. Example: https://plex.example.com (default: False)

**Comment by flying-sausages** [comment]
My bad, thanks for the info!
