### ISSUE TITLE
Bug: Webmin service enable/disable toggle does not stick

### ISSUE THREAD

**Issue by flying-sausages** [liaralabs/swizzin_dashboard#9]
![image](https://user-images.githubusercontent.com/23618693/82266070-2da23b80-9958-11ea-9f01-1562153373e8.png)

```
~$ sudo systemctl enable webmin
webmin.service is not a native service, redirecting to systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable webmin
```

Might be something about this that makes things weird in the panel. It doesn't "toggle" and stay enabled.

**Comment by martinleopold** [comment]
As a consequence Webmin cannot be disabled from the dashboard. See screen recording: https://i.imgur.com/Eur0fji.mp4

**Comment by raverdave-2k** [comment]
Getting the same, thought it might be something local to me, glad to know it's not.

**Comment by KillaKev** [comment]
In case anyone with a systemd system comes across this and wants to fix it. 

`sudo systemctl stop webmin
`

Create a new file: /etc/systemd/system/webmin.service with your preferred text editor and put the following

```
[Unit]
Description=Webmin

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/etc/webmin/start
ExecStop=/etc/webmin/stop
ExecReload=/etc/webmin/reload

[Install]
WantedBy=multi-user.target
```

Then run the following commands:

```
sudo mv /etc/init.d/webmin /etc/init.d/webmin.save

sudo systemctl daemon-reload

sudo systemctl start webmin.service
```

Now the toggle in the panel should work just fine.

**Comment by flying-sausages** [comment]
We could actually update that in the main repo, @liaralabs whacha thnk

**Comment by steve51184** [comment]
> In case anyone with a systemd system comes across this and wants to fix it.
> 
> `sudo systemctl stop webmin `
> 
> Create a new file: /etc/systemd/system/webmin.service with your preferred text editor and put the following
> 
> ```
> [Unit]
> Description=Webmin
> 
> [Service]
> Type=oneshot
> RemainAfterExit=yes
> ExecStart=/etc/webmin/start
> ExecStop=/etc/webmin/stop
> ExecReload=/etc/webmin/reload
> 
> [Install]
> WantedBy=multi-user.target
> ```
> 
> Then run the following commands:
> 
> ```
> sudo mv /etc/init.d/webmin /etc/init.d/webmin.save
> 
> sudo systemctl daemon-reload
> 
> sudo systemctl start webmin.service
> ```
> 
> Now the toggle in the panel should work just fine.

Any update for that fix and it no longer seems to be working.. webmin no longer starts at all

**Comment by gyCfjSnO** [comment]
Any update on this I am having same issue

**Comment by d3vilsown** [comment]
Same problem here...

**Comment by daanbreur** [comment]
everyone has this of its same for you

**Comment by liaralabs** [comment]
Webmin now ships a systemd service -- this is no longer an issue on the latest webmin.
